services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/HlapecMihad/PRAKTIKUM2/FrontEnd
    branch: main
    buildCommand: docker build -t frontend ./FrontEnd/reactjs-real-estate-template-master
    envVars:
      - key: NODE_ENV
        value: development

  - type: web
    name: backend
    env: docker
    repo: https://github.com/HlapecMihad/PRAKTIKUM2/nepremicnine
    branch: main
    buildCommand: docker build -t backend ./nepremicnine
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:admin@dbcluster.d2ungtz.mongodb.net/nepremicnine?retryWrites=true&w=majority

  - type: web
    name: python
    env: docker
    repo: https://github.com/HlapecMihad/PRAKTIKUM2/ScraperPart
    branch: main
    buildCommand: docker build -t python ./ScraperPart
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:admin@dbcluster.d2ungtz.mongodb.net/nepremicnine?retryWrites=true&w=majority

  - type: pserv
    name: mongo
    env: docker
    repo: https://github.com/HlapecMihad/PRAKTIKUM2/mongo
    branch: main
    disk:
      name: mongo_data
      mountPath: /nepremicnine/nepremicnine
      sizeGB: 10
