services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/your-repo/frontend
    branch: main
    buildCommand: docker build -t frontend ./FrontEnd/reactjs-real-estate-template-master
    startCommand: docker run -p 3000:3000 frontend
    envVars:
      - key: NODE_ENV
        value: development
    volumes:
      - path: /app
        mountPath: ./FrontEnd/reactjs-real-estate-template-master
      - path: /app/node_modules

  - type: web
    name: backend
    env: docker
    repo: https://github.com/your-repo/backend
    branch: main
    buildCommand: docker build -t backend ./nepremicnine
    startCommand: docker run -p 8180:8180 backend
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:admin@dbcluster.d2ungtz.mongodb.net/nepremicnine?retryWrites=true&w=majority

  - type: web
    name: python
    env: docker
    repo: https://github.com/your-repo/python
    branch: main
    buildCommand: docker build -t python ./ScraperPart
    startCommand: docker run -p 80:80 python
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://admin:admin@dbcluster.d2ungtz.mongodb.net/nepremicnine?retryWrites=true&w=majority

  - type: pserv
    name: mongo
    env: docker
    repo: https://github.com/your-repo/mongo
    branch: main
    startCommand: docker run -p 27017:27017 mongo:4.4
    disk:
      name: mongo_data
      mountPath: /nepremicnine/nepremicnine
      sizeGB: 10
