name: Weekly Scraper

on:
  schedule:
    - cron: '30 14 * * 4'  # Runs every Sunday at midnight
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ScraperPart/requirements.txt

      - name: Run scraper script
        run: python ScraperPart/main/scraper_vse_skupaj.py
