name: Weekly Scraper

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-edge:latest
        options: --privileged
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ScraperPart/requirements.txt
          pip install webdriver-manager

      - name: Wait for Selenium to be ready
        run: |
          timeout 300s bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/localhost/4444; do sleep 5; done'

      - name: Run scraper script
        env:
          PATH: /usr/local/bin:$PATH
        run: python ScraperPart/main/scraper_vse_skupaj.py

